<button id="popup-btn">ADD NEW CARD</button>

<div id="popup-container" style="display: none;">
    <div id="popup-content">
        <div id="close-container">&times;</div>
        <div id="header">Add New Card</div>
        <hr>
        <div id="flex">
            <div id="cart-type">Cart Type<input type="text" id="carttype"></div>
            <div id="card-holder">Cart Holder Name<input type="text" id="cartholdername"></div>
        </div>
        <div id="card-no">
            Card Number<input type="text" id="cardno" placeholder="Card Number">
        </div>
        <div id="flexflex">
            <div id="valid-thur">
                Valid Thur<input type="date" id="date">
            </div>
            <div>
                <input type="text" id="file" placeholder="cvv">
            </div>
        </div>
        <hr>
        <div id="addtocart"><button id="add-to-cart">ADD CARD</button></div>
    </div>
</div>
,
